spring:
  application:
    name: pink-backend

  datasource:
    url: jdbc:mysql://localhost:3306/pink_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    aws:
      region:
        static: us-east-1
      sqs:
        endpoint: http://localhost:4566
        queue-name: pink-queue