blank_issues_enabled: false
issue_templates:
  - name: "Feature Request"
    description: "새로운 기능을 제안하는 템플릿"
    file: feature.md

  - name: "Bug Fix"
    description: "버그 수정 요청 템플릿"
    file: fix.md
